@Library('ci-libs') _
pipeline {
  agent { label 'team-alpha' }
  stages {
    stage('Build') {
      steps {
        buildNotify('SUCCESS', 'Team Alpha build started')
        dockerBuild('team-alpha-image:latest')
      }
    }
  }
}
